# PCA: Principal Component Analysis

In [7]:
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]

X_centered

array([[-2.5, -2.5, -2.5, -2.5, -2.5],
       [ 2.5,  2.5,  2.5,  2.5,  2.5]])

In [8]:
W2 = Vt.T[:, :2]
X2D = X_centered.dot(W2)

X2D

array([[-5.59016994,  0.        ],
       [ 5.59016994,  0.        ]])

In [9]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
X2D = pca.fit_transform(X)

pca.explained_variance_ratio_

array([1.00000000e+00, 6.31088724e-33])

In [12]:
pca2 = PCA(n_components=0.95)
pca2.fit(X)
cumsum = np.cumsum(pca2.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1

d

1