# PCA: Principal Component Analysis

In [6]:
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])


X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]

c1

array([1., 0., 0., 0., 0.])

In [10]:
W2 = Vt.T[:, :2]
X2D = X_centered.dot(W2)

X2D

array([[0., 0.],
       [0., 0.]])

In [11]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
X2D = pca.fit_transform(X)

X2D

/home/ange/WORKSPACE/AI/0-Hands-on-Machine-Learning-with-Scikit-Learn-Keras-TensorFlow/my_env/lib/python3.6/site-packages/sklearn/decomposition/_pca.py:470: RuntimeWarning: invalid value encountered in true_divide
  explained_variance_ratio_ = explained_variance_ / total_var


array([[0., 0.],
       [0., 0.]])